### ISSUE TITLE
Institution api and projects for an institution

### ISSUE THREAD

**Issue by MortenHofft** [localcontexts/localcontextshub#137]
Hello, I'm exploring your API based on a meeting I had with Meredith from your team. It looks very nice.

At GBIF we manage a database of institutions.
An example entry: https://scientific-collections.gbif.org/institution/ad7d1a18-2ef8-4b2c-a302-5888fe9a2e1a
That institution has a corresponding entry in LC: https://localcontextshub.org/institutions/view/49/

I see that it has an `Open To Collaboration` mark and a single project associated. So i tried to get that via the API to show on our institution page as a small example

But:
I couldn't find any institution endpoint described in
https://localcontextshub.org/api/v1/ or https://github.com/localcontexts/localcontextshub/wiki/API-Documentation
And the projects associated with that entry (I assume ID 49) returns empty `[]`
https://localcontextshub.org/api/v1/projects/institutions/49/

Could you possibly point me in the right direction please?

Thank you

**Comment by arojas1** [comment]
Hello Morten, 

I would recommend taking a look at our [API Guide](https://localcontexts.org/support/api-guide/) as it lays out a bit more all the calls possible via the API and how to submit them.

In regards to the API call you tried, the reason that project was not showing under the API for the institution is because that API call only shows projects that were created by that institution account. The project that is showing there was created by a researcher account and then shared with that institution, which is why it doesn't show on the call but shows on the profile for that institution. 

If you are interested in looking at the API call for that specific project, I would recommend using the API call for project information. For that project, it would be https://localcontextshub.org/api/v1/projects/d503af03-cad2-4a3a-9e29-c32490881c5b/. You can get this by finding the Project ID on that [Project's Public Page](https://localcontextshub.org/projects/d503af03-cad2-4a3a-9e29-c32490881c5b/).

I hope this helps! Please let us know if you have any other questions.

Best,
Ashley

**Comment by MortenHofft** [comment]
Thanks @arojas1 
So no public API to get the [institution details](https://localcontextshub.org/institutions/view/49/) 
I suppose that means we won't be able to add LC to our institution pages at this point. 

In theory we could use https://localcontextshub.org/api/v1/projects/institutions/49/, but we would miss out on researcher projects as well as the information living on the institution (sounds like that `open to collaboration` is sitting on the institution object and is unaccessible through the API).

**Comment by arojas1** [comment]
@MortenHofft, maybe we can meet to discuss this more? Because you can still add information on to your institution pages but they would have to be pulled by Project ID. This is done in this way because a Project can refer to an entire collection, a group of items, or one item. If you are pulling information based only on the institution ID, there would be an additional manual process to have to determine which Project ID should be related to which collection/item(s). However, maybe understanding what it is you are trying to do would help me understand the need for this call to include projects created by others. We can always make updates to the API calls as needs to users increase or change.

The Open to Collaborate has it's own [call](https://localcontextshub.org/api/v1/notices/open_to_collaborate) on the API, it is not tied to a Project or account particularly because anyone can add this to their account to indicate they are open to collaborating with communities.

Let me know if you would like to meet to discuss your implementation questions or ideas.

**Comment by MortenHofft** [comment]
Thank you @arojas1 - I believe I will have a chance to talk to someone from your team in person later this month. I had simply hoped to prepare a bit by exploring the API and implement some ideas. It can wait. Thank you for your time.
